sudo: required
dist: trusty

services:
- docker

install:
- docker-compose pull
- docker-compose build

script:
- sudo docker-compose run --no-deps --rm web python manage.py makemigrations core_api accounts --noinput
- sudo docker-compose run --no-deps --rm web python manage.py migrate --noinput
- sudo docker-compose run --no-deps --rm web python manage.py test -settings=saleslog_rest.testing
