sudo: required
dist: trusty

services:
- docker

install:
- docker-compose pull
- docker-compose build

script:
- sudo docker-compose run --rm web python manage.py makemigrations core_api accounts --settings=saleslog_rest.testing --noinput
- sudo docker-compose run --rm web python manage.py migrate --settings=saleslog_rest.testing --noinput
- sudo docker-compose run --rm web python manage.py test --settings=saleslog_rest.testing
