# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180922_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('sales', 'sales'), ('admin', 'admin'), ('manager', 'manager'), ('super', 'super')], default='sales', max_length=32, verbose_name='user type'),
        ),
    ]
