# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.TextField(null=True)),
                ('statuses', models.TextField(null=True)),
                ('chats', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('Ticket', 'Ticket'), ('Master', 'Master')], default='Ticket', max_length=10)),
                ('tag', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('payment_done', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=32)),
                ('chat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Engineer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Equipment')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Part')),
            ],
        ),
        migrations.CreateModel(
            name='RepairNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(default='', max_length=6)),
                ('chain', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('fields', models.TextField(default='')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.RepairNetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Chat')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Repair')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Status')),
                ('support', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.Support')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Chain')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='network',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.RepairNetwork'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='network',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.RepairNetwork'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='network',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_api.RepairNetwork'),
        ),
        migrations.AddField(
            model_name='chain',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.Customer'),
        ),
    ]
