# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20181005_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Support', 'Support'), ('Network', 'Network')], max_length=32)),
                ('model_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Relation')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.StatusType'),
        ),
    ]
