# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20181016_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Chain'),
        ),
    ]
