# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_auto_20181217_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
