# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20181217_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='logo',
            field=models.FileField(default='', upload_to='support_logos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='tag',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.Chain'),
        ),
    ]
