# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_auto_20181218_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='color',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
