# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_support_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='color',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='support_logos'),
        ),
    ]
